#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = swww-daemon & swaync
exec-once = ~/.config/hypr/scripts/launch.sh
exec-once = hypridle -c ~/.config/hypr/configs/hypridle.conf
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

#Alt + Tab
exec-once = snappy-switcher --daemon
exec-once = swayosd-server
