
# Hyprpaper configuration
# See https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

# Preload your favorite wallpapers
# preload = /path/to/wallpaper.png

# Set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
# wallpaper = monitor,/path/to/wallpaper.png

# Enable splash text rendering over the wallpaper
splash = false

# Fully disable IPC
# ipc = off
